import * as fs from "fs/promises";
import * as path from "path";
import archiver from "archiver";

export async function createProjectZip(
  projectPath: string,
  projectName: string
): Promise<Buffer> {
  return new Promise(async (resolve, reject) => {
    try {
      const archive = archiver("zip", { 
        zlib: { level: 9 },
        forceLocalTime: true,
        forceZip64: false
      });
      const chunks: Buffer[] = [];

      archive.on("data", (chunk: Buffer) => chunks.push(chunk));
      archive.on("end", () => resolve(Buffer.concat(chunks)));
      archive.on("error", reject);
      archive.on("warning", (err) => {
        if (err.code === "ENOENT") {
          console.warn("Archive warning:", err);
        } else {
          reject(err);
        }
      });

      // Check if project path exists and is accessible
      try {
        await fs.access(projectPath);
      } catch (error) {
        console.warn(`Project path ${projectPath} not accessible, creating empty project`);
        
        // Create basic project structure
        const readme = generateReadme(projectName);
        archive.append(readme, { name: `${projectName}/README.md` });
        
        // Add a basic package.json if it's a Node.js project
        const packageJson = {
          name: projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-"),
          version: "1.0.0",
          description: "AI-generated project",
          main: "index.js",
          scripts: {
            start: "node index.js"
          }
        };
        archive.append(JSON.stringify(packageJson, null, 2), { 
          name: `${projectName}/package.json` 
        });
        
        archive.finalize();
        return;
      }

      // Filter out sensitive and unnecessary files
      const excludePatterns = [
        /node_modules/,
        /\.git$/,
        /\.env/,
        /\.log$/,
        /\.tmp$/,
        /\.cache/,
        /dist$/,
        /build$/,
        /coverage$/,
        /\.nyc_output/,
        /\.DS_Store$/,
        /Thumbs\.db$/
      ];

      // Add project files with filtering
      archive.glob("**/*", {
        cwd: projectPath,
        ignore: ["node_modules/**", ".git/**", "*.log", ".env*"],
        dot: false,
        follow: false
      }, { prefix: projectName });

      // Generate and add README.md
      const readme = generateReadme(projectName);
      archive.append(readme, { name: `${projectName}/README.md` });

      archive.finalize();
    } catch (error) {
      reject(error);
    }
  });
}

function generateReadme(projectName: string): string {
  return `# ${projectName}

This project was created and enhanced using Code AI Agent.

## About

This repository contains code that has been generated, refactored, and improved with the help of AI assistance.

## Features

- AI-powered code generation
- Intelligent refactoring and optimization
- Automated documentation
- Git integration with AI-assisted commits

## Getting Started

1. Clone this repository
2. Install dependencies (if applicable)
3. Follow the setup instructions in the project files

## AI Assistance

This project was built with the help of AI to:
- Generate boilerplate code
- Implement features and functionality
- Optimize performance and code quality
- Create comprehensive documentation

## Contributing

Feel free to contribute to this project by:
- Reporting bugs
- Suggesting new features
- Submitting pull requests

---

Generated by Code AI Agent - Powered by Google Gemini
`;
}

export async function saveUploadedFile(
  file: { originalname: string; buffer: Buffer },
  destinationPath: string
): Promise<string> {
  const fileName = file.originalname;
  const filePath = path.join(destinationPath, fileName);
  
  // Ensure destination directory exists
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  
  // Write file content
  await fs.writeFile(filePath, file.buffer);
  
  return filePath;
}

export function detectFileLanguage(fileName: string): string {
  const ext = path.extname(fileName).toLowerCase();
  const languageMap: Record<string, string> = {
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".py": "python",
    ".java": "java",
    ".cpp": "cpp",
    ".c": "c",
    ".cs": "csharp",
    ".go": "go",
    ".rs": "rust",
    ".php": "php",
    ".rb": "ruby",
    ".html": "html",
    ".css": "css",
    ".json": "json",
    ".md": "markdown",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".xml": "xml",
    ".sh": "bash",
  };
  
  return languageMap[ext] || "text";
}